version: '2'

volumes:
  database_data:
    driver: local

services:
  nginx:
    build: C:\Users\tsantora\PhpstormProjects\Dev-Enviro\pfv\nginx\
    ports:
      - 8080:80
    volumes:
      - C:\Users\tsantora\PhpstormProjects\Dev-Enviro\pfv\nginx\default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build: C:\Users\tsantora\PhpstormProjects\Dev-Enviro\pfv\php\
    expose:
      - 9000
    volumes:
      -  C:\Users\tsantora\PhpstormProjects\Dev-Enviro\pfv\public_html\:/var/www/html
      -  C:\Users\tsantora\PhpstormProjects\Dev-Enviro\pfv\php\php.ini:/usr/local/etc/php/php.ini
  mysql:
    image: mysql:latest
    expose:
      - 3306
    volumes:
      - C:\Users\tsantora\PhpstormProjects\Dev-Enviro\pfv\mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project